// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vswynclwyvlezaygrpiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzd3luY2x3eXZsZXpheWdycGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyOTUzMzksImV4cCI6MjA1NTg3MTMzOX0.LthM4XUFkVBKtBDzzvhqGjdXz-1gWTmNf93TQtD1SeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);